import shutil
import subprocess
from pathlib import Path

import pytest

from scribe.types import Segment, Transcript

HAS_FFMPEG = shutil.which("ffmpeg") is not None and shutil.which("ffprobe") is not None
requires_ffmpeg = pytest.mark.skipif(not HAS_FFMPEG, reason="ffmpeg/ffprobe not on PATH")


@pytest.fixture
def transcript() -> Transcript:
    return Transcript(
        segments=[
            Segment(0.0, 2.5, " Hello there."),
            Segment(2.5, 5.25, " This is a test."),
            Segment(5.25, 6.0, "   "),  # whitespace-only: must be skipped by writers
            Segment(6.0, 3671.5, " And a long one."),
        ],
        language="en",
        duration=3671.5,
        backend="faster-whisper",
        model="base",
    )


@pytest.fixture
def tone_wav(tmp_path: Path) -> Path:
    """A real 2-second 16 kHz mono WAV, generated by ffmpeg."""
    out = tmp_path / "tone.wav"
    subprocess.run(
        ["ffmpeg", "-nostdin", "-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=2",
         "-ar", "16000", "-ac", "1", str(out)],
        capture_output=True, check=True,
    )
    return out


@pytest.fixture
def silent_video(tmp_path: Path) -> Path:
    """A 1-second video with no audio stream at all."""
    out = tmp_path / "mute.mp4"
    subprocess.run(
        ["ffmpeg", "-nostdin", "-y", "-f", "lavfi", "-i", "color=c=black:s=64x64:d=1",
         "-pix_fmt", "yuv420p", str(out)],
        capture_output=True, check=True,
    )
    return out


@pytest.fixture
def video_with_audio(tmp_path: Path) -> Path:
    """A 1-second video that does have an audio track — the normal case."""
    out = tmp_path / "clip.mp4"
    subprocess.run(
        ["ffmpeg", "-nostdin", "-y",
         "-f", "lavfi", "-i", "color=c=blue:s=64x64:d=1",
         "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
         "-pix_fmt", "yuv420p", "-shortest", str(out)],
        capture_output=True, check=True,
    )
    return out
